---
driver:
  name: dokken

provisioner:
  name: policyfile_zero
  policyfile: policyfiles/Policyfile.rb

platforms:
  - name: ubuntu-24.04

suites:
  - name: default
    verifier:
      name: inspec
