name 'docker_host'
maintainer 'DevOps Course'
maintainer_email 'devops-course@example.invalid'
license 'Apache-2.0'
description 'Docker host configuration'
version '0.1.0'
chef_version '>= 18.0'
depends 'base'
