services:
  docker:
    image: docker:29.6.1-dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
      - ../:/workspace/devops-hands-on-practices:rw
    command: ["--storage-driver", "overlay2"]

  jenkins:
    build:
      context: ./jenkins
    environment:
      DOCKER_CERT_PATH: /certs/client
      DOCKER_HOST: tcp://docker:2376
      DOCKER_TLS_VERIFY: "1"
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false
      JENKINS_ADMIN_ID: admin
      JENKINS_ADMIN_PASSWORD: admin
      JENKINS_SAMPLE_JOB_NAME: docker-course-sample-app
    ports:
      - "8085:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
      - ../:/workspace/devops-hands-on-practices:rw
    depends_on:
      - docker

volumes:
  jenkins-data:
  jenkins-docker-certs:
