apiVersion: v1
kind: Service
metadata:
  name: course-nginx
  namespace: docker-course
  labels:
    app.kubernetes.io/name: course-nginx
    app.kubernetes.io/part-of: docker-course
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: course-nginx
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP

