apiVersion: v1
kind: Namespace
metadata:
  name: docker-course-packaging
  labels:
    app.kubernetes.io/part-of: docker-course
    docker-course.dev/lesson: "15-helm-kustomize-artifact-repositories"
