server {
  listen 8080;

  location = /healthz {
    proxy_pass http://api:5000/healthz;
  }

  location / {
    if ($http_x_role = "") {
      return 401;
    }

    proxy_set_header X-Role $http_x_role;
    proxy_pass http://api:5000;
  }
}
