apiVersion: v1
kind: ServiceAccount
metadata:
  name: course-web
  namespace: docker-course-gitops
  labels:
    app.kubernetes.io/name: course-web
    app.kubernetes.io/part-of: docker-course
automountServiceAccountToken: false
