apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: course-app-secret
  namespace: docker-course-secrets
  labels:
    app.kubernetes.io/part-of: docker-course
    docker-course.dev/lesson: "13-vaults-and-secrets-managers"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-dev
    kind: SecretStore
  target:
    name: course-app-secret
    creationPolicy: Owner
  data:
    - secretKey: api-token
      remoteRef:
        key: secret/docker-course
        property: api_token
