apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: course-app-secret
  namespace: docker-course-secrets
  labels:
    app.kubernetes.io/part-of: docker-course
    docker-course.dev/lesson: "13-vaults-and-secrets-managers"
spec:
  encryptedData:
    api-token: AgByPlaceholderEncryptedValueDoNotApply
  template:
    metadata:
      name: course-app-secret
      namespace: docker-course-secrets
    type: Opaque
