apiVersion: v1
kind: ServiceAccount
metadata:
  name: k3s-demo
  namespace: docker-course-k3s
  labels:
    app.kubernetes.io/name: k3s-demo
    app.kubernetes.io/part-of: docker-course
automountServiceAccountToken: false
