apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-web
  namespace: docker-course-packaging
spec:
  replicas: 3
  template:
    metadata:
      annotations:
        docker-course.dev/overlay: prod
    spec:
      containers:
        - name: nginx
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
