apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: k3s-demo-ingress
  namespace: docker-course-k3s
  labels:
    app.kubernetes.io/name: k3s-demo
    app.kubernetes.io/part-of: docker-course
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: k3s-demo
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 8080
