replicaCount: 3

ingress:
  enabled: true

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

content:
  title: Helm Prod
  message: Prod values rendered by Helm.
